name: CD Pipeline - Docker Hub Push

on:
  push:
    branches:
      - main
      - feature/initial_upload
    tags:
      - 'v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Nginx image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            freddocker443/package_release_1:latest
            freddocker443/package_release_1:${{ github.sha }}
            freddocker443/package_release_1:${{ github.ref_name }}
